title: insert-your-title-here Workshop
logo: /assets/img/logo.gif
description: Workshop is held Wednesday (Aug 3) and Thursday (Aug 4) from 1-4 P.M.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
